table Dim_Channel
	lineageTag: 4e1ab4ab-3b9a-49cf-a4d3-929ad28fc82d

	column Channel
		dataType: string
		lineageTag: 875f51ed-94bd-4000-a91a-4a801f5f78b3
		sourceColumn: Channel

	column Campaign
		dataType: string
		lineageTag: 6f962e50-983a-4419-95cf-580e892828c6
		sourceColumn: Campaign

	column Channel_Campaign_Key
		dataType: string
		isKey
		lineageTag: bb1bc17c-b9c1-42d0-b0c4-ae579f2498bc
		sourceColumn: Channel_Campaign_Key

	partition Dim_Channel = m
		mode: import
		source = let Source = Excel.Workbook(File.Contents("C:\\AI-Agent-Team\\retail_sales_2025.xlsx"), null, true), SalesTable = Source{[Item="SalesTable",Kind="Table"]}[Data], Selected = Table.SelectColumns(SalesTable, {"Sales_Channel", "Campaign"}), Renamed = Table.RenameColumns(Selected, {{"Sales_Channel", "Channel"}}), ChangedType = Table.TransformColumnTypes(Renamed, {{"Channel", type text}, {"Campaign", type text}}), Deduped = Table.Distinct(ChangedType), AddKey = Table.AddColumn(Deduped, "Channel_Campaign_Key", each [Channel] & "|" & [Campaign], type text) in AddKey

